@startuml
class Клиент
class Сотрудник
class Администратор
class Товар
class Категория
class Заказ
class ПозицияЗаказа
class ЗаявкаНаРемонт
class Статус
Клиент "1" -- "*" Заказ
Клиент "1" -- "*" ЗаявкаНаРемонт
Категория "1" -- "*" Товар
Заказ "1" -- "*" ПозицияЗаказа
Товар "1" -- "*" ПозицияЗаказа
Сотрудник "1" -- "*" ЗаявкаНаРемонт
Статус "1" -- "*" Заказ
Статус "1" -- "*" ЗаявкаНаРемонт
Администратор ..> Товар : управляет
Администратор ..> Заказ : контролирует
@enduml
